replicasCount: 1
fullName: "solenopsys-ds-postgres"
selectorLabel: "solenopsys-ds-postgres"

service:
  port: 5432

storage:
  volumeName: postgres-volume
  volumeClimeName: postgres-pvc
  storageSize: 1Gi
  accessModes: "ReadWriteOnce"
  hostPath: "/opt/dgraph-volume"
  storageClass: "local-path"

containers:
  postgres:
    name: postgres
    image: postgres:14.4
    pullPolicy: IfNotPresent
    secret: alexstorm-pg-password


